version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: building-asset-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: building_asset
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - building-asset-net

  redis:
    image: redis:5-alpine
    container_name: building-asset-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - building-asset-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: building-asset-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend/config:/app/config
      - ./backend/uploads:/app/uploads
    networks:
      - building-asset-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: building-asset-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080/api/v1
    networks:
      - building-asset-net

volumes:
  mysql_data:
  redis_data:

networks:
  building-asset-net:
    driver: bridge